version: "3"
services:
  database:
    image: postgres:9.4.5
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    command: bundle exec rails s -p 3000 -b "0.0.0.0"
    working_dir: /var/www/consul
    depends_on:
      - database
    ports:
      - "5000:3000"
    volumes:
      - .:/var/www/consul
      - bundle:/usr/local/bundle
    env_file: .env
volumes:
  bundle:
  db_data: